[pr_description]
publish_labels = true
add_original_user_description = true
generate_ai_title = false

[pr_reviewer]
require_tests_review = true
require_estimate_effort_to_review = true
num_code_suggestions = 4

[pr_code_suggestions]
num_code_suggestions = 4

[github]
pr_commands = [
    "/describe --pr_description.add_original_user_description=true --pr_description.keep_original_user_title=true",
    "/review --pr_reviewer.num_code_suggestions=4",
    "/improve",
]
